"""Initial revision

Revision ID: c2e8403cb964
Revises: 
Create Date: 2025-10-02 15:43:52.621944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e8403cb964'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('maker', sa.String(length=10), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('type_', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_table('laptop',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('speed', sa.SmallInteger(), nullable=False),
    sa.Column('ram', sa.SmallInteger(), nullable=False),
    sa.Column('hd', sa.REAL(), nullable=False),
    sa.Column('price', postgresql.MONEY(), nullable=True),
    sa.Column('screen', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['model'], ['product.model'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('pc',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('speed', sa.SmallInteger(), nullable=False),
    sa.Column('ram', sa.SmallInteger(), nullable=False),
    sa.Column('hd', sa.REAL(), nullable=False),
    sa.Column('cd', sa.String(length=10), nullable=False),
    sa.Column('price', postgresql.MONEY(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['product.model'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('printer',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('price', postgresql.MONEY(), nullable=True),
    sa.ForeignKeyConstraint(['model'], ['product.model'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printer')
    op.drop_table('pc')
    op.drop_table('laptop')
    op.drop_table('product')
    # ### end Alembic commands ###
