"""Add enums to types

Revision ID: cc13adbf839b
Revises: c2e8403cb964
Create Date: 2025-10-08 15:21:05.679124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc13adbf839b'
down_revision: Union[str, Sequence[str], None] = 'c2e8403cb964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    printer_type = sa.Enum('JET', 'LASER', 'MATRIX', name='printertype')
    product_type = sa.Enum('LAPTOP', 'PC', 'PRINTER', name='producttype')

    printer_type.create(op.get_bind(), checkfirst=True)
    product_type.create(op.get_bind(), checkfirst=True)

    op.execute("""
        ALTER TABLE printer
        ALTER COLUMN type_ TYPE printertype 
        USING type_::printertype
    """)

    op.execute("""
        ALTER TABLE product
        ALTER COLUMN type_ TYPE producttype 
        USING type_::producttype
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'type_',
               existing_type=sa.Enum('LAPTOP', 'PC', 'PRINTER', name='producttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('printer', 'type_',
               existing_type=sa.Enum('JET', 'LASER', 'MATRIX', name='printertype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS producttype")
    op.execute("DROP TYPE IF EXISTS printertype")
